### ISSUE TITLE
Issue in heroku deployment

### ISSUE THREAD

**Issue by craziks-creator** [chellarao-chowdary/Nitp_website-scraping#6]
Requested runtime (Python 3.7.6) is not available for this stack (heroku-20).

**Comment by craziks-creator** [comment]
And no both token, api hash, api id available in app.json

**Comment by chellarao-chowdary** [comment]
> And no both token, api hash, api id available in app.json

You can get API hash, API id from https://core.telegram.org/api/obtaining_api_id

And bot token from BotFather - https://t.me/BotFather

But its just an API, To run this API - bot token and API id or hash are not required.

**Comment by chellarao-chowdary** [comment]
> Requested runtime (Python 3.7.6) is not available for this stack (heroku-20).

Clone the repo and update the runtime with the supported version.

Or you can deploy it in Vercel. (Refer to readme)
